// Generated by https://quicktype.io

export interface Products {
  _id:         string;
  product:    string;
  mark:       string;
  price:      string;
  details:    string;
  characters: string;
  alt_img?:   string;
}

